; -*- Mode: Lisp; Syntax: Common-Lisp; Package: PSEUDOSCHEME-GUILE -*-

;;;; More of libguile's primitives: lists and association lists, sorting,
;;;; numbers, symbols, strings, vectors, bit vectors and arrays, the
;;;; operating system, and the C halves of (ice-9 ports) and friends,
;;;; which Guile's modules install with load-extension.

(in-package "PSEUDOSCHEME-GUILE")

(defun scheme-equal (a b) (ps:scheme-equal-p a b))
(defun scheme-eqv (a b) (or (eql a b) (and (numberp a) (numberp b) (= a b) (eq (type-of a) (type-of b)))))

;;; ------------------------------------------------------------------
;;; Lists

(macrolet ((alist-procs (prefix test)
	     (flet ((name (s) (format nil "~A~A" prefix s)))
	       `(progn
		  (defguile ,(name "-ref") (alist key)
		    (let ((entry (assoc key alist :test ,test)))
		      (if entry (cdr entry) ps:false)))
		  (defguile ,(name "-set!") (alist key value)
		    (let ((entry (assoc key alist :test ,test)))
		      (if entry
			  (progn (setf (cdr entry) value) alist)
			  (acons key value alist))))
		  (defguile ,(name "-remove!") (alist key)
		    (let ((entry (assoc key alist :test ,test)))
		      (if entry (delete entry alist :test #'eq :count 1) alist)))))))
  (alist-procs "assq" #'eq)
  (alist-procs "assv" #'scheme-eqv)
  (alist-procs "assoc" #'scheme-equal))

(defguile "sloppy-assq" (key alist)
  (or (find-if (lambda (e) (and (consp e) (eq (car e) key))) alist) ps:false))
(defguile "sloppy-assv" (key alist)
  (or (find-if (lambda (e) (and (consp e) (scheme-eqv (car e) key))) alist) ps:false))
(defguile "sloppy-assoc" (key alist)
  (or (find-if (lambda (e) (and (consp e) (scheme-equal (car e) key))) alist) ps:false))

(defguile "delq" (x list) (remove x list :test #'eq))
(defguile "delv" (x list) (remove x list :test #'scheme-eqv))
(defguile "delete" (x list &optional (eq ps:false))
  (if (truthy eq)
      (remove-if (lambda (y) (truthy (funcall eq x y))) list)
      (remove x list :test #'scheme-equal)))
(defguile "delq!" (x list) (delete x list :test #'eq))
(defguile "delv!" (x list) (delete x list :test #'scheme-eqv))
(defguile "delete!" (x list &optional (eq ps:false))
  (if (truthy eq)
      (delete-if (lambda (y) (truthy (funcall eq x y))) list)
      (delete x list :test #'scheme-equal)))
(defguile "delq1!" (x list) (delete x list :test #'eq :count 1))
(defguile "delv1!" (x list) (delete x list :test #'scheme-eqv :count 1))
(defguile "delete1!" (x list) (delete x list :test #'scheme-equal :count 1))
(defguile "list-head" (list k) (subseq list 0 k))
(defguile "list-copy" (list) (copy-list list))
(defguile "list-cdr-ref" (list k) (nthcdr k list))
(defguile "list-cdr-set!" (list k v) (setf (cdr (nthcdr k list)) v) *unspecified*)
(defguile "list-set!" (list k v) (setf (nth k list) v) *unspecified*)
(defguile "append!" (&rest lists) (apply #'nconc lists))
(defguile "reverse!" (list &optional (tail '())) (nreconc list tail))
(defguile "filter" (pred list) (remove-if-not (lambda (x) (truthy (funcall pred x))) list))
(defguile "filter!" (pred list) (delete-if-not (lambda (x) (truthy (funcall pred x))) list))
(defguile "make-list" (n &optional (fill *unspecified*)) (make-list n :initial-element fill))

;;; ------------------------------------------------------------------
;;; Sorting: (sort sequence less), lists and vectors

(defun guile-less (less) (lambda (a b) (truthy (funcall less a b))))

(defguile "sort" (seq less)
  (if (listp seq)
      (stable-sort (copy-list seq) (guile-less less))
      (stable-sort (copy-seq seq) (guile-less less))))
(defguile "sort!" (seq less) (stable-sort seq (guile-less less)))
(setf (gethash "stable-sort" *guile-primitives*) (gethash "sort" *guile-primitives*)
      (gethash "stable-sort!" *guile-primitives*) (gethash "sort!" *guile-primitives*)
      (gethash "sort-list" *guile-primitives*) (gethash "sort" *guile-primitives*)
      (gethash "sort-list!" *guile-primitives*) (gethash "sort!" *guile-primitives*))
(defguile "merge" (a b less)
  (merge (if (listp a) 'list 'vector) (copy-seq a) (copy-seq b) (guile-less less)))
(defguile "merge!" (a b less)
  (merge (if (listp a) 'list 'vector) a b (guile-less less)))
(defguile "sorted?" (seq less)
  (let ((list (coerce seq 'list)))
    (bool (loop for (a b) on list while (cdr (member b list :test #'eq))
		never (and b (truthy (funcall less b a)))))))
(defguile "restricted-vector-sort!" (v less start end)
  (setf (subseq v start end) (stable-sort (subseq v start end) (guile-less less)))
  *unspecified*)

;;; ------------------------------------------------------------------
;;; Numbers

(defun euclid (n d)
  (multiple-value-bind (q r) (floor n d)
    (if (minusp r) (values (1+ q) (- r d)) (values q r))))
(defun euclidean (n d)
  ;; remainder always >= 0
  (if (plusp d) (floor n d) (ceiling n d)))

(defguile "euclidean/" (n d) (euclidean n d))
(defguile "euclidean-quotient" (n d) (values (euclidean n d)))
(defguile "euclidean-remainder" (n d) (nth-value 1 (euclidean n d)))
(defguile "ceiling/" (n d) (ceiling n d))
(defguile "ceiling-quotient" (n d) (values (ceiling n d)))
(defguile "ceiling-remainder" (n d) (nth-value 1 (ceiling n d)))
(defguile "round/" (n d) (round n d))
(defguile "round-quotient" (n d) (values (round n d)))
(defguile "round-remainder" (n d) (nth-value 1 (round n d)))
(defun centered (n d)
  (multiple-value-bind (q r) (round n d)
    (let ((half (/ (abs d) 2)))
      (cond ((>= r half) (values (+ q (signum d)) (- r (abs d))))
	    ((< r (- half)) (values (- q (signum d)) (+ r (abs d))))
	    (t (values q r))))))
(defguile "centered/" (n d) (centered n d))
(defguile "centered-quotient" (n d) (values (centered n d)))
(defguile "centered-remainder" (n d) (nth-value 1 (centered n d)))
(defguile "integer-expt" (n k) (expt n k))
(defguile "modulo-expt" (n k m)
  (let ((result 1) (base (mod n m)))
    (loop while (plusp k)
	  do (when (oddp k) (setq result (mod (* result base) m)))
	     (setq base (mod (* base base) m) k (ash k -1)))
    result))
(defguile "log10" (x) (log x 10d0))
(defguile "sinh" (x) (sinh x))
(defguile "cosh" (x) (cosh x))
(defguile "tanh" (x) (tanh x))
(defguile "asinh" (x) (asinh x))
(defguile "acosh" (x) (acosh x))
(defguile "atanh" (x) (atanh x))
(defguile "inf?" (x) (bool (and (floatp x) (sb-ext:float-infinity-p x))))

(defvar *guile-random-state* (make-random-state t))
(defguile "random" (n &optional (state *guile-random-state*))
  (random n (if (random-state-p state) state *guile-random-state*)))
(defguile "random:uniform" (&optional (state *guile-random-state*))
  (random 1d0 (if (random-state-p state) state *guile-random-state*)))
(defguile "random:normal" (&optional (state *guile-random-state*))
  (let ((s (if (random-state-p state) state *guile-random-state*)))
    (* (sqrt (* -2 (log (- 1d0 (random 1d0 s))))) (cos (* 2 pi (random 1d0 s))))))
(defguile "random:exp" (&optional (state *guile-random-state*))
  (- (log (- 1d0 (random 1d0 (if (random-state-p state) state *guile-random-state*))))))
(defguile "copy-random-state" (&optional (state *guile-random-state*)) (make-random-state state))
(defguile "seed->random-state" (seed)
  (let ((s (sb-ext:seed-random-state (if (stringp seed) (sxhash seed) seed)))) s))
(defguile "random-state-from-platform" () (make-random-state t))
(defguile "random-state->datum" (state) (declare (ignore state)) ps:false)
(defguile "datum->random-state" (datum) (declare (ignore datum)) (make-random-state t))

;;; ------------------------------------------------------------------
;;; Symbols

(defguile "make-symbol" (name) (make-symbol (ps::invert-case name)))
(defguile "symbol-interned?" (s) (bool (symbol-package s)))
(defguile "string-ci->symbol" (s) (ssym (string-downcase s)))
(defguile "symbol-pref" (s) (get s 'guile-pref ps:false))
(defguile "symbol-pset!" (s v) (setf (get s 'guile-pref) v) *unspecified*)
(defguile "symbol-fref" (s) (get s 'guile-fref ps:false))
(defguile "symbol-fset!" (s v) (setf (get s 'guile-fref) v) *unspecified*)

;;; ------------------------------------------------------------------
;;; Strings (most are SRFI 13's: see GUILE-LIBRARY-BINDINGS)

(defun char-matcher (x)
  (cond ((characterp x) (lambda (c) (char= c x)))
	((functionp x) (lambda (c) (truthy (funcall x c))))
	(t (let ((contains (library-value "(srfi 14)" "char-set-contains?")))
	     (lambda (c) (truthy (funcall contains x c)))))))

(defguile "string-split" (s pred)
  (let ((match (char-matcher pred)) (parts '()) (start 0))
    (loop for i from 0 below (length s)
	  when (funcall match (char s i))
	    do (push (subseq s start i) parts) (setq start (1+ i)))
    (push (subseq s start) parts)
    (nreverse parts)))
(defguile "string-rindex" (s pred &optional (start 0) (end (length s)))
  (let ((match (char-matcher pred)))
    (or (loop for i from (1- end) downto start when (funcall match (char s i)) return i)
	ps:false)))
(defguile "substring/copy" (s start &optional (end (length s))) (subseq s start end))
(defguile "substring/read-only" (s start &optional (end (length s))) (subseq s start end))
(defguile "string-append/shared" (&rest strings) (apply #'concatenate 'string strings))
(defguile "string-bytes-per-char" (s) (if (every (lambda (c) (< (char-code c) 256)) s) 1 4))
(defguile "string-utf8-length" (s) (length (sb-ext:string-to-octets s :external-format :utf-8)))
(defguile "string-capitalize" (s) (string-capitalize s))
(defguile "string-capitalize!" (s) (nstring-capitalize s))
(defguile "string-copy!" (to at from &optional (start 0) (end (length from)))
  (replace to from :start1 at :start2 start :end2 end) *unspecified*)
(defguile "string-fill!" (s c &optional (start 0) (end (length s)))
  (fill s c :start start :end end) *unspecified*)
(defguile "substring-move!" (from start end to at)
  (replace to from :start1 at :start2 start :end2 end) *unspecified*)
(defguile "char-is-both?" (c) (bool (and (both-case-p c) (not (upper-case-p c)) (not (lower-case-p c)))))

;;; ------------------------------------------------------------------
;;; Vectors

(defguile "vector-move-left!" (from start end to at)
  (replace to from :start1 at :start2 start :end2 end) *unspecified*)
(defguile "vector-move-right!" (from start end to at)
  (replace to from :start1 at :start2 start :end2 end) *unspecified*)
(defguile "vector-copy!" (to at from &optional (start 0) (end (length from)))
  (replace to from :start1 at :start2 start :end2 end) *unspecified*)
(defguile "vector-fill!" (v x &optional (start 0) (end (length v)))
  (fill v x :start start :end end) *unspecified*)

;;; ------------------------------------------------------------------
;;; Bit vectors

(defguile "bitvector?" (x) (bool (typep x 'simple-bit-vector)))
(defguile "make-bitvector" (n &optional (fill ps:false))
  (make-array n :element-type 'bit :initial-element (if (truthy fill) 1 0)))
(defguile "bitvector" (&rest bits)
  (make-array (length bits) :element-type 'bit :initial-contents (mapcar (lambda (b) (if (truthy b) 1 0)) bits)))
(defguile "list->bitvector" (bits)
  (make-array (length bits) :element-type 'bit :initial-contents (mapcar (lambda (b) (if (truthy b) 1 0)) bits)))
(defguile "bitvector->list" (v) (map 'list (lambda (b) (bool (= b 1))) v))
(defguile "bitvector-length" (v) (length v))
(defguile "bitvector-ref" (v i) (bool (= 1 (sbit v i))))
(defguile "bitvector-bit-set?" (v i) (bool (= 1 (sbit v i))))
(defguile "bitvector-bit-clear?" (v i) (bool (= 0 (sbit v i))))
(defguile "bitvector-set!" (v i b) (setf (sbit v i) (if (truthy b) 1 0)) *unspecified*)
(defguile "bitvector-set-bit!" (v i) (setf (sbit v i) 1) *unspecified*)
(defguile "bitvector-clear-bit!" (v i) (setf (sbit v i) 0) *unspecified*)
(defguile "bitvector-fill!" (v b) (fill v (if (truthy b) 1 0)) *unspecified*)
(defguile "bitvector-set-all-bits!" (v) (fill v 1) *unspecified*)
(defguile "bitvector-clear-all-bits!" (v) (fill v 0) *unspecified*)
(defguile "bitvector-flip-all-bits!" (v) (bit-not v v) *unspecified*)
(defguile "bitvector-count" (v) (count 1 v))
(defguile "bitvector-copy" (v &optional (start 0) (end (length v))) (subseq v start end))
(defguile "bitvector-position" (v b &optional (start 0))
  (or (position (if (truthy b) 1 0) v :start start) ps:false))
(defguile "bit-count" (b v) (count (if (truthy b) 1 0) v))
(defguile "bit-position" (b v start) (or (position (if (truthy b) 1 0) v :start start) ps:false))
(defguile "bit-invert!" (v) (bit-not v v) *unspecified*)

;;; ------------------------------------------------------------------
;;; Arrays: Lisp arrays (a vector is a rank-1 array)

(defguile "array?" (x) (bool (and (arrayp x) (not (stringp x)) t)))
(defguile "typed-array?" (x type) (declare (ignore type)) (bool (arrayp x)))
(defguile "array-rank" (a) (if (arrayp a) (array-rank a) 0))
(defguile "array-dimensions" (a) (array-dimensions a))
(defguile "array-length" (a) (array-dimension a 0))
(defguile "array-ref" (a &rest indices) (let ((x (apply #'aref a indices))) (if (typep a 'bit-vector) (bool (= x 1)) x)))
(defguile "array-set!" (a v &rest indices) (setf (apply #'aref a indices) v) *unspecified*)
(defguile "array-in-bounds?" (a &rest indices) (bool (apply #'array-in-bounds-p a indices)))
(defguile "make-array" (fill &rest bounds)
  (make-array (mapcar (lambda (b) (if (consp b) (1+ (- (cadr b) (car b))) b)) bounds) :initial-element fill))
(defguile "make-typed-array" (type fill &rest bounds)
  (declare (ignore type))
  (make-array (mapcar (lambda (b) (if (consp b) (1+ (- (cadr b) (car b))) b)) bounds) :initial-element fill))
(defguile "array->list" (a)
  (labels ((walk (dims indices)
	     (if (null dims)
		 (apply #'aref a (reverse indices))
		 (loop for i below (car dims) collect (walk (cdr dims) (cons i indices))))))
    (walk (array-dimensions a) '())))
(defguile "list->array" (rank list)
  (labels ((dims (x r) (if (zerop r) '() (cons (length x) (dims (car x) (1- r))))))
    (make-array (dims list (if (integerp rank) rank (length rank))) :initial-contents list)))
(defguile "array-fill!" (a x)
  (let ((v (make-array (array-total-size a) :displaced-to a))) (fill v x)) *unspecified*)
(defguile "array-type" (a) (declare (ignore a)) ps:true)
(defguile "array-for-each" (proc a &rest more)
  (dotimes (i (array-total-size a))
    (apply proc (row-major-aref a i) (mapcar (lambda (b) (row-major-aref b i)) more)))
  *unspecified*)
(defguile "array-map!" (dest proc &rest sources)
  (dotimes (i (array-total-size dest))
    (setf (row-major-aref dest i) (apply proc (mapcar (lambda (b) (row-major-aref b i)) sources))))
  *unspecified*)
(defguile "array-copy!" (src dest)
  (dotimes (i (array-total-size src)) (setf (row-major-aref dest i) (row-major-aref src i)))
  *unspecified*)

;;; ------------------------------------------------------------------
;;; The operating system

(defun system-error (subr &optional (errno (sb-alien:extern-alien "errno" sb-alien:int)))
  (guile-error (ssym "system-error") subr "~A" (list (sb-int:strerror errno)) (list errno)))

(defguile "getenv" (name) (or (sb-posix:getenv name) ps:false))
(defguile "setenv" (name value)
  (if (truthy value) (sb-posix:setenv name value 1) (sb-posix:unsetenv name))
  *unspecified*)
(defguile "putenv" (string)
  (let ((i (position #\= string)))
    (if i
	(sb-posix:setenv (subseq string 0 i) (subseq string (1+ i)) 1)
	(sb-posix:unsetenv string)))
  *unspecified*)
(defguile "environ" (&optional env)
  (declare (ignore env))
  (sb-ext:posix-environ))
(defguile "getcwd" () (sb-posix:getcwd))
(defguile "chdir" (dir)
  (sb-posix:chdir dir)
  (setf *default-pathname-defaults* (uiop:ensure-directory-pathname (sb-posix:getcwd)))
  *unspecified*)
(defguile "getpid" () (sb-posix:getpid))
(defguile "getppid" () (sb-posix:getppid))
(defguile "getuid" () (sb-posix:getuid))
(defguile "geteuid" () (sb-posix:geteuid))
(defguile "getgid" () (sb-posix:getgid))
(defguile "getegid" () (sb-posix:getegid))
(defguile "getlogin" () (or (sb-posix:getenv "USER") ps:false))
(defguile "gethostname" () (machine-instance))
(defguile "umask" (&optional mode) (if mode (sb-posix:umask mode) (let ((m (sb-posix:umask 0))) (sb-posix:umask m) m)))
(defguile "mkdir" (path &optional (mode #o777)) (sb-posix:mkdir path mode) *unspecified*)
(defguile "rmdir" (path) (sb-posix:rmdir path) *unspecified*)
(defguile "rename-file" (old new) (sb-posix:rename old new) *unspecified*)
(defguile "delete-file" (path) (sb-posix:unlink path) *unspecified*)
(defguile "link" (old new) (sb-posix:link old new) *unspecified*)
(defguile "symlink" (old new) (sb-posix:symlink old new) *unspecified*)
(defguile "readlink" (path) (sb-posix:readlink path))
(defguile "chmod" (path mode) (sb-posix:chmod path mode) *unspecified*)
(defguile "copy-file" (old new) (uiop:copy-file old new) *unspecified*)
(defguile "access?" (path how)
  (bool (handler-case (progn (sb-posix:access path how) t) (sb-posix:syscall-error () nil))))
(defguile "basename" (path &optional suffix)
  (let* ((p (string-right-trim "/" path))
	 (base (if (zerop (length p)) "/" (subseq p (1+ (or (position #\/ p :from-end t) -1))))))
    (if (and (stringp suffix) (> (length base) (length suffix))
	     (string= suffix base :start2 (- (length base) (length suffix))))
	(subseq base 0 (- (length base) (length suffix)))
	base)))
(defguile "dirname" (path)
  (let* ((p (string-right-trim "/" path))
	 (i (position #\/ p :from-end t)))
    (cond ((zerop (length p)) "/")
	  ((null i) ".")
	  ((zerop i) "/")
	  (t (string-right-trim "/" (subseq p 0 i))))))
(defguile "canonicalize-path" (path)
  (let ((p (probe-file path)))
    (unless p (system-error "canonicalize-path" sb-posix:enoent))
    (let ((s (namestring p))) (if (and (> (length s) 1) (char= (char s (1- (length s))) #\/)) (subseq s 0 (1- (length s))) s))))
(defguile "system-file-name-convention" () (ssym "posix"))
(defguile "file-encoding" (port) (declare (ignore port)) ps:false)

(defun stat-vector (st)
  (vector (sb-posix:stat-dev st) (sb-posix:stat-ino st) (sb-posix:stat-mode st)
	  (sb-posix:stat-nlink st) (sb-posix:stat-uid st) (sb-posix:stat-gid st)
	  (sb-posix:stat-rdev st) (sb-posix:stat-size st) (sb-posix:stat-atime st)
	  (sb-posix:stat-mtime st) (sb-posix:stat-ctime st) 4096
	  (ceiling (sb-posix:stat-size st) 512)
	  (ssym (let ((m (logand (sb-posix:stat-mode st) sb-posix:s-ifmt)))
		  (cond ((= m sb-posix:s-ifdir) "directory") ((= m sb-posix:s-iflnk) "symlink")
			((= m sb-posix:s-ifchr) "char-special") ((= m sb-posix:s-ifblk) "block-special")
			((= m sb-posix:s-ififo) "fifo") ((= m sb-posix:s-ifsock) "socket")
			(t "regular"))))
	  (logand (sb-posix:stat-mode st) #o7777)
	  0 0 0))
(defguile "stat" (path &optional (exception-on-error ps:true))
  (handler-case (stat-vector (if (streamp path) (sb-posix:fstat (sb-sys:fd-stream-fd path)) (sb-posix:stat path)))
    (sb-posix:syscall-error (e)
      (if (truthy exception-on-error)
	  (system-error "stat" (sb-posix:syscall-errno e))
	  ps:false))))
(defguile "lstat" (path)
  (handler-case (stat-vector (sb-posix:lstat path))
    (sb-posix:syscall-error (e) (system-error "lstat" (sb-posix:syscall-errno e)))))

(defstruct (directory-stream (:constructor make-directory-stream (entries))) entries (open t))
(defguile "opendir" (path)
  (let ((d (sb-posix:opendir path)) (entries '()))
    (unwind-protect
	 (loop for ent = (sb-posix:readdir d)
	       until (sb-alien:null-alien ent)
	       do (push (sb-posix:dirent-name ent) entries))
      (sb-posix:closedir d))
    (make-directory-stream (nreverse entries))))
(defguile "readdir" (d)
  (if (directory-stream-entries d) (pop (directory-stream-entries d)) ps:eof-object))
(defguile "closedir" (d) (setf (directory-stream-open d) nil) *unspecified*)
(defguile "directory-stream?" (x) (bool (directory-stream-p x)))
(defguile "rewinddir" (d) (declare (ignore d)) *unspecified*)

(defguile "system" (&optional (command ps:false))
  (if (truthy command)
      (nth-value 2 (uiop:run-program (list "/bin/sh" "-c" command) :ignore-error-status t
				     :output :interactive :error-output :interactive :input :interactive))
      ps:true))
(defguile "system*" (&rest args)
  (* 256 (nth-value 2 (uiop:run-program args :ignore-error-status t
					:output :interactive :error-output :interactive :input :interactive))))
(defguile "status:exit-val" (status) (if (zerop (logand status #x7f)) (ash status -8) ps:false))
(defguile "status:term-sig" (status) (let ((s (logand status #x7f))) (if (zerop s) ps:false s)))
(defguile "status:stop-sig" (status) (declare (ignore status)) ps:false)
(defguile "sleep" (n) (sleep n) 0)
(defguile "usleep" (n) (sleep (/ n 1000000)) 0)
(defguile "gettimeofday" ()
  (multiple-value-bind (sec usec) (sb-ext:get-time-of-day) (cons sec usec)))
(defguile "times" ()
  (vector (get-internal-real-time) (get-internal-run-time) 0 0 0))
(defguile "uname" ()
  (vector (software-type) (machine-instance) (software-version) "" (machine-type)))
(defguile "isatty?" (port) (declare (ignore port)) ps:false)
(defguile "kill" (pid sig) (sb-posix:kill pid sig) *unspecified*)
(defguile "strerror" (n) (sb-int:strerror n))

(defun tm-vector (seconds zone-offset dst)
  (multiple-value-bind (s m h d mo y dow) (decode-universal-time (+ seconds #.(encode-universal-time 0 0 0 1 1 1970 0)) 0)
    (vector s m h d (1- mo) (- y 1900) (mod (1+ dow) 7)
	    (- (encode-universal-time 0 0 0 d mo y 0) (encode-universal-time 0 0 0 1 1 y 0) -0)
	    (if dst 1 0) zone-offset (if (zerop zone-offset) "UTC" "LOCAL"))))
(defguile "gmtime" (time) (tm-vector time 0 nil))
(defguile "localtime" (time &optional zone)
  (declare (ignore zone))
  (multiple-value-bind (s m h d mo y dow dst tz)
      (decode-universal-time (+ time #.(encode-universal-time 0 0 0 1 1 1970 0)))
    (declare (ignore s m h d mo y dow))
    (let ((offset (* 3600 (- tz (if dst 1 0)))))
      (tm-vector (- time offset) offset dst))))

;;; ------------------------------------------------------------------
;;; Odds and ends

(defguile "defined?" (sym &optional (module ps:false))
  (let ((v (module-variable* (if (truthy module) module *current-module*) sym)))
    (bool (and v (not (eq (gvariable-value v) +unbound+))))))
(defguile "procedure-minimum-arity" (p)
  (declare (ignore p))
  (list 0 0 ps:true))
(defguile "object->string" (x &optional printer)
  (if (functionp printer)
      (with-output-to-string (s) (funcall printer x s))
      (with-output-to-string (s) (funcall ps:*scheme-write* x s))))
(defguile "syntax-source" (s)
  (let ((v (and (syntax-object-p s) (syntax-object-sourcev s))))
    (if (simple-vector-p v)
	(list (cons (ssym "filename") (svref v 0)) (cons (ssym "line") (svref v 1))
	      (cons (ssym "column") (svref v 2)))
	ps:false)))
(defguile "make-guardian" ()
  (let ((objects '()))
    (lambda (&optional (x nil x-p))
      (if x-p (progn (push x objects) *unspecified*) ps:false))))
(defguile "make-stack" (&rest args) (declare (ignore args)) ps:false)
(defguile "stack?" (x) (declare (ignore x)) ps:false)
(defguile "frame?" (x) (declare (ignore x)) ps:false)
(defguile "backtrace" (&rest args) (declare (ignore args)) *unspecified*)
(defguile "display-backtrace" (&rest args) (declare (ignore args)) *unspecified*)
(defguile "display-application" (&rest args) (declare (ignore args)) *unspecified*)
(defguile "display-error" (frame port subr message args rest)
  (declare (ignore frame rest))
  (when (truthy subr) (format port "In procedure ~A: " subr))
  (write-string (apply #'simple-format ps:false message (if (listp args) args '())) port)
  (terpri port)
  *unspecified*)
(defguile "eval-string" (string &optional (module ps:false))
  (with-input-from-string (in string)
    (let ((result *unspecified*))
      (loop for form = (guile-read in)
	    until (eq form ps:eof-object)
	    do (setq result (guile-eval form module)))
      result)))
(defguile "gettext" (msg &rest args) (declare (ignore args)) msg)
(defguile "ngettext" (msg plural n &rest args) (declare (ignore args)) (if (= n 1) msg plural))
(defguile "textdomain" (&rest args) (declare (ignore args)) ps:false)
(defguile "bindtextdomain" (&rest args) (declare (ignore args)) ps:false)
(defguile "bind-textdomain-codeset" (&rest args) (declare (ignore args)) ps:false)
(defguile "setlocale" (&rest args) (declare (ignore args)) "C")
(defguile "%package-data-dir" () (namestring (uiop:pathname-parent-directory-pathname *guile-source-directory*)))
(defguile "%library-dir" () "")
(defguile "%site-dir" () "")
(defguile "%global-site-dir" () "")
(defguile "%site-ccache-dir" () "")
(defguile "%resolve-variable" (spec module)
  (or (module-variable* module (if (consp spec) (cdr spec) spec)) ps:false))
(defguile "module-import-interface" (module sym)
  (declare (ignore module sym))
  ps:false)
(defguile "memoized-typecode" (x) (declare (ignore x)) 0)
(defguile "unmemoize-expression" (x) x)
(defguile "system-async-mark" (&rest args) (declare (ignore args)) *unspecified*)
(defguile "sigaction" (&rest args) (declare (ignore args)) (cons ps:false 0))
(defguile "restore-signals" () *unspecified*)
(defguile "alarm" (n) (declare (ignore n)) 0)
(defguile "load-compiled" (file) (declare (ignore file)) ps:false)

;;; ------------------------------------------------------------------
;;; load-extension: libguile's init functions for modules partly in C.
;;; Each defines its bindings in the current module.

(defvar *extensions* (make-hash-table :test 'equal)
  "C init function name -> function returning ((name . value) ...).")

(defmacro defextension (name &body body)
  `(setf (gethash ,name *extensions*) (lambda () ,@body)))

(defguile "load-extension" (library init)
  (declare (ignore library))
  (let ((ext (gethash init *extensions*)))
    (when ext
      (loop for (name . value) in (funcall ext)
	    do (define-in-module *current-module* (ssym name) value)))
    (fill-unbound-exports init)
    *unspecified*))

(defvar *extension-primitives* (make-hash-table :test 'equal)
  "Procedures of Guile's C extensions that aren't in the root module:
name -> function, for FILL-UNBOUND-EXPORTS.")

(defvar *missing-extension-names* '()
  "(init . name): what load-extension couldn't define.")

(defun fill-unbound-exports (init)
  "Give each variable of the current module that is still unbound (the
module exports it, and its C half was to define it) the host's value of
that name, if the host has one."
  (let ((obarray (and (module-p* *current-module*) (module-slot *current-module* +module-obarray+))))
    (when (ghash-p obarray)
      (dolist (handle (ghash-handles obarray))
	(let ((name (car handle)) (v (cdr handle)))
	  (when (and (gvariable-p v) (eq (gvariable-value v) +unbound+))
	    (let ((s (ps:scheme-symbol-name name)))
	      (cond ((gethash s *extension-primitives*)
		     (setf (gvariable-value v) (gethash s *extension-primitives*)))
		    ((gethash s *guile-primitives*)
		     (setf (gvariable-value v) (gethash s *guile-primitives*)))
		    ((host-bound-p s) (setf (gvariable-value v) (psx:host-ref s)))
		    (t (push (cons init s) *missing-extension-names*))))))))))

(defextension "scm_init_ice_9_control"
  (list (cons "suspendable-continuation?" (lambda (tag) (bool (psx::find-prompt tag))))))

;;; (rnrs bytevectors gnu)'s bytevector-slice: a copy here, where Guile's
;;; shares the bytes
(defextension "scm_init_bytevectors"
  (list (cons "bytevector-slice"
	      (lambda (bv offset &optional (size (- (length bv) offset)))
		(subseq bv offset (+ offset size))))))

;;; (ice-9 i18n): the C locale only

(defun string-compare-fn (test &optional fold)
  (lambda (a b &optional locale)
    (declare (ignore locale))
    (bool (funcall test (if fold (string-downcase a) a) (if fold (string-downcase b) b)))))

(defun char-compare-fn (test &optional fold)
  (lambda (a b &optional locale)
    (declare (ignore locale))
    (bool (funcall test (if fold (char-downcase a) a) (if fold (char-downcase b) b)))))

(defstruct (locale (:constructor make-locale* ())) )
(defmethod print-object ((l locale) stream) (write-string "#<locale C>" stream))
(defvar *c-locale* (make-locale*))

(defextension "scm_init_i18n"
  (append
   (list
    (cons "make-locale" (lambda (&rest args) (declare (ignore args)) *c-locale*))
    (cons "locale?" (lambda (x) (bool (locale-p x))))
    (cons "%global-locale" *c-locale*)
    (cons "string-locale<?" (string-compare-fn #'string<))
    (cons "string-locale>?" (string-compare-fn #'string>))
    (cons "string-locale-ci<?" (string-compare-fn #'string< t))
    (cons "string-locale-ci>?" (string-compare-fn #'string> t))
    (cons "string-locale-ci=?" (string-compare-fn #'string= t))
    (cons "char-locale<?" (char-compare-fn #'char<))
    (cons "char-locale>?" (char-compare-fn #'char>))
    (cons "char-locale-ci<?" (char-compare-fn #'char< t))
    (cons "char-locale-ci>?" (char-compare-fn #'char> t))
    (cons "char-locale-ci=?" (char-compare-fn #'char= t))
    (cons "char-locale-downcase" (lambda (c &optional l) (declare (ignore l)) (char-downcase c)))
    (cons "char-locale-upcase" (lambda (c &optional l) (declare (ignore l)) (char-upcase c)))
    (cons "char-locale-titlecase" (lambda (c &optional l) (declare (ignore l)) (char-upcase c)))
    (cons "string-locale-downcase" (lambda (s &optional l) (declare (ignore l)) (string-downcase s)))
    (cons "string-locale-upcase" (lambda (s &optional l) (declare (ignore l)) (string-upcase s)))
    (cons "string-locale-titlecase" (lambda (s &optional l) (declare (ignore l)) (string-capitalize s)))
    (cons "locale-string->integer"
	  (lambda (s &optional (base 10) l)
	    (declare (ignore l))
	    (multiple-value-bind (n end) (parse-integer s :radix base :junk-allowed t)
	      (if n (values n end) (values ps:false 0)))))
    (cons "locale-string->inexact"
	  (lambda (s &optional l)
	    (declare (ignore l))
	    (let ((n (ps:parse-scheme-number s 10)))
	      (if n (values (float n 1d0) (length s)) (values ps:false 0)))))
    (cons "locale-encoding" (lambda (&optional l) (declare (ignore l)) "UTF-8"))
    (cons "locale-decimal-point" (lambda (&optional l) (declare (ignore l)) "."))
    (cons "locale-thousands-separator" (lambda (&optional l) (declare (ignore l)) ""))
    (cons "locale-digit-grouping" (lambda (&optional l) (declare (ignore l)) '()))
    (cons "locale-am-string" (lambda (&optional l) (declare (ignore l)) "AM"))
    (cons "locale-pm-string" (lambda (&optional l) (declare (ignore l)) "PM"))
    (cons "locale-yes-regexp" (lambda (&optional l) (declare (ignore l)) "^[yY]"))
    (cons "locale-no-regexp" (lambda (&optional l) (declare (ignore l)) "^[nN]")))
   (loop for (name names) in '(("locale-day" ("Sunday" "Monday" "Tuesday" "Wednesday" "Thursday" "Friday" "Saturday"))
			       ("locale-day-short" ("Sun" "Mon" "Tue" "Wed" "Thu" "Fri" "Sat"))
			       ("locale-month" ("January" "February" "March" "April" "May" "June" "July"
						"August" "September" "October" "November" "December"))
			       ("locale-month-short" ("Jan" "Feb" "Mar" "Apr" "May" "Jun" "Jul" "Aug"
						      "Sep" "Oct" "Nov" "Dec")))
	 collect (let ((names names))
		   (cons name (lambda (n &optional l) (declare (ignore l)) (nth (1- n) names)))))))

(defguile "raise" (signal) (sb-posix:kill (sb-posix:getpid) signal) ps:true)

;;; File descriptors and processes

(defun fd-port (fd mode)
  (sb-sys:make-fd-stream fd :input (find #\r mode) :output (or (find #\w mode) (find #\a mode))
			    :external-format :utf-8 :buffering :full :auto-close t))
(defguile "pipe" ()
  (multiple-value-bind (in out) (sb-posix:pipe)
    (cons (fd-port in "r") (fd-port out "w"))))
(defguile "open-fdes" (path flags &optional (mode #o666)) (sb-posix:open path flags mode))
(defguile "open" (path flags &optional (mode #o666))
  (let ((fd (sb-posix:open path flags mode)))
    (fd-port fd (cond ((logtest flags sb-posix:o-rdwr) "rw")
		      ((logtest flags sb-posix:o-wronly) "w")
		      (t "r")))))
(defguile "close-fdes" (fd) (sb-posix:close fd) *unspecified*)
(defguile "close" (fd/port)
  (if (integerp fd/port) (sb-posix:close fd/port) (close fd/port))
  *unspecified*)
(defguile "waitpid" (pid &optional (options 0))
  (multiple-value-bind (p status) (sb-posix:waitpid pid options)
    (cons p status)))
(defguile "sync" () *unspecified*)
(defguile "fsync" (x) (declare (ignore x)) *unspecified*)
(defguile "flock" (&rest args) (declare (ignore args)) *unspecified*)
(defguile "mkstemp" (template &optional mode)
  (declare (ignore mode))
  (multiple-value-bind (fd name) (sb-posix:mkstemp template)
    (let ((p (fd-port fd "rw")))
      (setf (gethash p *port-filenames*) name)
      p)))
(setf (gethash "mkstemp!" *guile-primitives*) (gethash "mkstemp" *guile-primitives*))
(defguile "mkdtemp" (template) (sb-posix:mkdtemp template))
(defguile "tmpnam" () (format nil "/tmp/guile-~36R" (random (expt 36 8))))
(defguile "tmpfile" () (funcall (gethash "mkstemp" *guile-primitives*) (copy-seq "/tmp/guile-XXXXXX")))
(defguile "setuid" (id) (sb-posix:setuid id) *unspecified*)
(defguile "setgid" (id) (sb-posix:setgid id) *unspecified*)
(defguile "getpgrp" () (sb-posix:getpgrp))
(defguile "getgroups" () (vector (sb-posix:getgid)))
(defguile "getpw" (&optional user)
  (let ((pw (cond ((null user) nil)
		  ((integerp user) (sb-posix:getpwuid user))
		  (t (sb-posix:getpwnam user)))))
    (if pw
	(vector (sb-posix:passwd-name pw) (sb-posix:passwd-passwd pw) (sb-posix:passwd-uid pw)
		(sb-posix:passwd-gid pw) (sb-posix:passwd-gecos pw) (sb-posix:passwd-dir pw)
		(sb-posix:passwd-shell pw))
	ps:false)))
(defguile "parse-path" (path &optional (tail '()))
  (if (and (stringp path) (plusp (length path)))
      (append (funcall (gethash "string-split" *guile-primitives*) path #\:) tail)
      tail))
(defguile "search-path" (path filename &optional (extensions '("")) require-exts)
  (declare (ignore require-exts))
  (or (loop for dir in path
	    do (loop for ext in (if (listp extensions) extensions '(""))
		     for f = (format nil "~A/~A~A" dir filename ext)
		     when (probe-file f) do (return-from nil f)))
      ps:false))
(defguile "procedure" (x)
  (if (typep x 'applicable-struct) (svref (astruct-slots x) 0) (wrong-type "procedure" 1 x)))

(defun strftime (format tm)
  (let ((s (svref tm 0)) (m (svref tm 1)) (h (svref tm 2)) (d (svref tm 3))
	(mo (svref tm 4)) (y (+ 1900 (svref tm 5))) (wd (svref tm 6)))
    (with-output-to-string (out)
      (loop with i = 0 while (< i (length format))
	    do (let ((c (char format i)))
		 (if (and (char= c #\%) (< (1+ i) (length format)))
		     (let ((d2 (char format (1+ i))))
		       (case d2
			 (#\Y (format out "~D" y)) (#\y (format out "~2,'0D" (mod y 100)))
			 (#\m (format out "~2,'0D" (1+ mo))) (#\d (format out "~2,'0D" d))
			 (#\e (format out "~2D" d))
			 (#\H (format out "~2,'0D" h)) (#\M (format out "~2,'0D" m))
			 (#\S (format out "~2,'0D" s))
			 (#\a (write-string (subseq (nth wd '("Sunday" "Monday" "Tuesday" "Wednesday" "Thursday" "Friday" "Saturday")) 0 3) out))
			 (#\A (write-string (nth wd '("Sunday" "Monday" "Tuesday" "Wednesday" "Thursday" "Friday" "Saturday")) out))
			 (#\b (write-string (subseq (nth mo '("January" "February" "March" "April" "May" "June" "July" "August" "September" "October" "November" "December")) 0 3) out))
			 (#\B (write-string (nth mo '("January" "February" "March" "April" "May" "June" "July" "August" "September" "October" "November" "December")) out))
			 (#\F (format out "~D-~2,'0D-~2,'0D" y (1+ mo) d))
			 (#\T (format out "~2,'0D:~2,'0D:~2,'0D" h m s))
			 (#\Z (write-string (svref tm 10) out))
			 (#\z (let ((off (- (svref tm 9)))) (format out "~A~2,'0D~2,'0D" (if (minusp off) "-" "+") (floor (abs off) 3600) (mod (floor (abs off) 60) 60))))
			 (#\% (write-char #\% out))
			 (t (write-char c out) (write-char d2 out)))
		       (incf i 2))
		     (progn (write-char c out) (incf i))))))))
(defguile "strftime" (format tm) (strftime format tm))
(defguile "mktime" (tm &optional zone)
  (declare (ignore zone))
  (let ((u (encode-universal-time (svref tm 0) (svref tm 1) (svref tm 2) (svref tm 3)
				  (1+ (svref tm 4)) (+ 1900 (svref tm 5)))))
    (cons (- u #.(encode-universal-time 0 0 0 1 1 1970 0)) tm)))
(defguile "tzset" () *unspecified*)
(defguile "primitive-fork" () (sb-posix:fork))
(defguile "execlp" (program &rest args)
  (sb-ext:run-program program (cdr args) :search t :output t :error t :input t)
  (sb-ext:exit :code 0))
(setf (gethash "execl" *guile-primitives*) (gethash "execlp" *guile-primitives*))
