;;; Tests for SRFI 100, from the examples in the SRFI document.  The
;;; examples redefine groups, so they are run in nested bodies.
(import (scheme base) (scheme case-lambda) (scheme process-context)
        (srfi 64) (srfi 100))

(define (examples)
  ;; The `x' is a read-write field.  The `y' is a read-only field.
  (define-lambda-object ppoint (x) y)
  (define pp (make-ppoint 10 20))
  (define color 'black)
  (test-equal 10 (pp 'x))
  (test-equal 20 (pp 'y))
  (pp 'x 11)
  (test-equal 11 (pp 'x))
  (test-error "read-only field" #t (pp 'y 22))
  (test-error "absent field" #t (pp 'z))
  (test-error "too few arguments" #t (make-ppoint 1))
  (test-error "too many arguments" #t (make-ppoint 1 2 3))

  ;; The parent group `ppoint' is an unamendable group.
  (test-error "incompatible read-write field" #t
    (let ()
      (define-lambda-object (cpoint ppoint) x y color)
      #f))

  (let ()
    ;; Automatic fields and virtual fields.
    (define-lambda-object (cpoint ppoint)
      (x) y
      (,color-init color) (,area-init (* x y))
      (`,color color) (`,area (* x y)))
    (define ap (make-cpoint 10 20))
    (test-error "constructor arity" #t (make-cpoint 3 33 'black))
    (test-equal '(10 20 black black 200 200)
      (map ap '(x y color-init color area-init area)))
    (ap 'x 30)
    (test-equal '(30 20 black black 200 600)
      (map ap '(x y color-init color area-init area)))
    (set! color 'white)
    (test-equal '(30 20 black white 200 600)
      (map ap '(x y color-init color area-init area)))

    (let ()
      ;; An automatic common field.
      (define-lambda-object (cpoint ppoint)
        (x) y
        ((,,color) color)
        (`,area (* x y))
        (,set/add (lambda (i j) (set! x (+ i x)) (set! y (+ j y)))))
      (define tp (make-cpoint 10 15))
      (define cp (make-cpoint 15 20))
      (test-equal '(10 15 white 150) (map tp '(x y color area)))
      (test-equal '(15 20 white 300) (map cp '(x y color area)))
      (cp 'color 'brown)
      ((cp 'set/add) 5 10)
      (test-equal '(20 30 brown 600) (map cp '(x y color area)))
      (test-equal '(10 15 brown 150) (map tp '(x y color area)))
      (test-equal "predicate, other group" #f (cpoint? ap))
      (test-equal #t (cpoint? tp))
      (test-equal #t (cpoint? cp))
      (test-equal "parent predicate" #t (ppoint? cp))
      (test-equal "predicate, non-object" #f (cpoint? car))
      (test-equal "predicate, non-procedure" #f (cpoint? 5))

      (let ()
        ;; An amendable parent, an optional hidden field, a virtual
        ;; field and an automatic field.
        (define-lambda-object (spoint (ppoint))
          (x 0) (y x) (z x) ('stack '())
          (`,pop (if (null? stack)
                     (error 'spoint "null stack" stack)
                     (let ((s (car stack))) (set! stack (cdr stack)) s)))
          (,push (lambda (s) (set! stack (cons s stack)))))
        (define sp0 (make-spoint))
        (define sp1 (make-spoint 5 55))
        (define sp (make-spoint-by-name 'z 100 'stack (list 'sunflower)))
        (test-equal '(0 0 0) (map sp0 '(x y z)))
        (test-equal '(5 55 5) (map sp1 '(x y z)))
        (test-equal '(0 0 100) (map sp '(x y z)))
        ((sp 'push) 'rose)
        ((sp 'push) 'lily)
        (test-equal 'lily (sp 'pop))
        (test-equal 'rose (sp 'pop))
        (test-equal 'sunflower (sp 'pop))
        (test-error "null stack" #t (sp 'pop))
        (test-error "hidden field" #t (sp 'stack))

        (let ()
          ;; Two amendable parents.
          (define-lambda-object (epoint (spoint) (cpoint))
            ((x) 5) ((y) 10) ((z) 15) ((planet) "earth")
            (,,color "brown")
            (',stack '())
            (`,area (* x y))
            (`,volume (* x y z))
            (`,pop (if (null? stack)
                       (error 'spoint "null stack" stack)
                       (let ((s (car stack))) (set! stack (cdr stack)) s)))
            (,push (lambda (s) (set! stack (cons s stack))))
            (,adbmal (lambda (f) (f x y z color planet (* x y) (* x y z))))
            (,set/add
             (case-lambda
              ((i j) (cond
                      ((and (string? i) (string? j)) (set! color i) (set! planet j))
                      ((and (number? i) (number? j)) (set! x (+ i x)) (set! y (+ j y)))
                      (else (error 'epoint "set/add: wrong data type" i j))))
              ((i j k) (set! x (+ i x)) (set! y (+ j y)) (set! z (+ k z))))))
          (define ep (make-epoint-by-name 'planet "jupiter"))
          (define tp2 (make-epoint 10 15 20))
          (test-equal '#(5 10 15 "brown" "jupiter" 50 750) ((ep 'adbmal) vector))
          (test-equal '#(10 15 20 "brown" "earth" 150 3000) ((tp2 'adbmal) vector))
          (test-equal '(11 30 20 0 5)
            (map (lambda (o) (o 'x)) (list pp ap cp sp ep)))
          (test-equal '(#t #t #t #t)
            (map (lambda (p) (p ep)) (list ppoint? cpoint? spoint? epoint?)))
          ((ep 'set/add) "red" "mars")
          (test-equal '(5 10 15 "red" "mars" 50 750) ((ep 'adbmal) list))
          (test-equal '(10 15 20 "red" "earth" 150 3000) ((tp2 'adbmal) list))
          ((ep 'set/add) 5 10)
          (test-equal '(10 20 15 "red" "mars" 200 3000) ((ep 'adbmal) list))
          ((ep 'set/add) 10 30 50)
          (test-equal '(20 50 65 1000 65000) (map ep '(x y z area volume)))
          (test-equal '(20 30 600) (map cp '(x y area)))
          ((cp 'set/add) 20 50)
          (test-equal '(40 80 3200) (map cp '(x y area)))
          (test-error "set/add arity" #t ((cp 'set/add) 10 100 1000))

          ;; The group procedure.
          (test-equal (list spoint cpoint) (epoint 'parent))
          (test-eq epoint? (epoint 'predicate))
          (test-equal '(x y z planet) (epoint 'read-write-field))
          (test-equal '(color area volume pop push adbmal set/add)
            (epoint 'read-only-field))
          (test-equal '() (epoint 'required-field))
          (test-equal '((x 5) (y 10) (z 15) (planet "earth"))
            (epoint 'optional-field))
          (test-equal '((color "brown")) (epoint 'common-field))
          (test-equal '((stack '())) (epoint 'hidden-field))
          (test-equal '(area volume pop)
            (map car (epoint 'virtual-field)))
          (test-equal '(color area volume pop stack push adbmal set/add)
            (map car (epoint 'automatic-field)))
          ;; The implementation gives a pair, where the SRFI shows a list.
          (test-eq make-epoint (car (epoint 'constructor)))
          (test-eq make-epoint-by-name (cdr (epoint 'constructor))))))))

(test-begin "srfi-100")
(examples)
(let ((failures (test-runner-fail-count (test-runner-current))))
  (test-end "srfi-100")
  (exit (if (zero? failures) 0 1)))
