;;; Tests for SRFI 105, curly-infix-expressions: the SRFI's examples.
;;; The syntax is the reader's; there's no library.
(import (scheme base) (scheme read) (scheme process-context) (srfi 64))
(define (r s) (read (open-input-string s)))
(test-begin "srfi-105")

(test-equal '(<= n 5) (r "{n <= 5}"))
(test-equal '(+ x 1) (r "{x + 1}"))
(test-equal '(+ a b c) (r "{a + b + c}"))
(test-equal '(,op x y z) (r "{x ,op y ,op z}"))
(test-equal '(eqv? x `a) (r "{x eqv? `a}"))
(test-equal '(eq? 'a b) (r "{'a eq? b}"))
(test-equal '(+ n-1 n-2) (r "{n-1 + n-2}"))
(test-equal '(* a (+ b c)) (r "{a * {b + c}}"))
(test-equal '(- (+ a b) c) (r "{{a + b} - c}"))
(test-equal '(and (> a 0) (>= b 1)) (r "{{a > 0} and {b >= 1}}"))
(test-equal '() (r "{}"))
(test-equal 5 (r "{5}"))
(test-equal '(- x) (r "{- x}"))
(test-equal '(>= (length x) 6) (r "{length(x) >= 6}"))
(test-equal '(+ (f x) (g y) (h z)) (r "{f(x) + g(y) + h(z)}"))
(test-equal '(+ (f a b) (g h)) (r "{(f a b) + (g h)}"))
(test-equal '(+ (f a b) (g h)) (r "{f(a b) + g(h)}"))
(test-equal ''(+ a (f b) x) (r "'{a + f(b) + x}"))
(test-equal '(/ (- a) b) (r "{(- a) / b}"))
(test-equal '(/ (- a) b) (r "{-(a) / b}"))
(test-equal '(cos q) (r "{cos(q)}"))
(test-equal '(e) (r "{e{}}"))
(test-equal '(pi) (r "{pi()}"))
(test-equal ''(f x) (r "{'f(x)}"))
(test-equal '(f (g (h x))) (r "{ (f (g h(x))) }"))
(test-equal '#(1 2 (f a) 4) (r "{#(1 2 f(a) 4)}"))
(test-equal '(f (h x)) (r "{(f #;g(x) h(x))}"))
(test-equal '(map - ns) (r "{(map - ns)}"))
(test-equal '(map - ns) (r "{map(- ns)}"))
(test-equal '(* n (factorial (- n 1))) (r "{n * factorial{n - 1}}"))
(test-equal '(* 2 (sin (- x))) (r "{2 * sin{- x}}"))
(test-equal '($nfx$ 3 + 4 +) (r "{3 + 4 +}"))
(test-equal '($nfx$ 3 + 4 + 5 +) (r "{3 + 4 + 5 +}"))
(test-equal '($nfx$ a . z) (r "{a . z}"))
(test-equal '($nfx$ a + b - c) (r "{a + b - c}"))
(test-equal '(read . options) (r "{read(. options)}"))
(test-equal '((a x) y) (r "{a(x)(y)}"))
(test-equal '($bracket-apply$ x a) (r "{x[a]}"))
(test-equal '($bracket-apply$ y a b) (r "{y[a b]}"))
(test-equal '((f (- n 1)) x) (r "{f{n - 1}(x)}"))
(test-equal '((f (- n 1)) (- y 1)) (r "{f{n - 1}{y - 1}}"))
(test-equal '($bracket-apply$ (f (- x)) y) (r "{f{- x}[y]}"))
(test-equal "#!curly-infix is whitespace" '(+ 1 2) (r "#!curly-infix {1 + 2}"))
(test-equal "outside braces, f(x) is two data" 'f (r "f(x)"))

;; and in code
(define (factorial n) (if {n <= 1} 1 {n * factorial{n - 1}}))
(test-equal 120 (factorial 5))
(test-equal 7 {1 + {2 * 3}})

(let ((failures (test-runner-fail-count (test-runner-current))))
  (test-end "srfi-105")
  (exit (if (zero? failures) 0 1)))
