;;; Tests for SRFI 107: the SRFI's translations, and the SXML made.
(import (scheme base) (scheme process-context) (srfi 64) (srfi 107))
(test-begin "srfi-107")

(test-equal '($xml-element$ () ($resolve-qname$ a) ($xml-attribute$ 'class "title")
                            "Result: " $<<$ sum $>>$ ".")
  '#<a class="title">Result: &[sum].</a>)
(test-equal '($xml-element$ ((prefix1 "URI1") (prefix2 "URI" $entity$:foo "2") (|| "DURI"))
                            ($resolve-qname$ a prefix2) "x")
  '#<prefix2:a xmlns:prefix1="URI1" xmlns:prefix2="URI&foo;2" xmlns="DURI">x</prefix2:a>)

(define sum 42)
(test-equal '(a (@ (class "title")) "Result: " 42 ".")
  #<a class="title">Result: &[sum].</a>)
(test-equal '(p "x" (br) "y") #<p>x<br/>y</p>)
(test-equal '(ul (li "one") (li "two")) #<ul><li>one</li><li>two</li></ul>)
(test-equal '(*COMMENT* " note ") #<!-- note -->)
(test-equal "a<b" #<![CDATA[a<b]]>)
(test-equal '(*PI* xml-stylesheet "href=\"s.css\"") #<?xml-stylesheet href="s.css"?>)
(test-equal '(svg:rect (@ (width "10"))) #<svg:rect width="10"/>)
(test-equal "<p class=\"x\">a &amp; b<br/></p>" (xml->string #<p class="x">a &amp; b<br/></p>))
(test-assert (xml-element? #<p/>))
(test-equal 'p (xml-element-name #<p k="v">t</p>))
(test-equal '((k "v")) (xml-element-attributes #<p k="v">t</p>))
(test-equal '("t") (xml-element-content #<p k="v">t</p>))

(let ((failures (test-runner-fail-count (test-runner-current))))
  (test-end "srfi-107")
  (exit (if (zero? failures) 0 1)))
