;;; Tests for SRFI 202, from the sample implementation's examples
;;; (reference/srfi-202/examples.scm).
(import (scheme base) (scheme process-context) (srfi 64) (srfi 202))

(define (results thunk) (call-with-values thunk list))

(define (examples)
  (test-equal #t (and-let* ()))
  (test-equal #t (and-let* ((even-two (even? 2)))))
  (test-equal #t (and-let* ((b+ (memq 'b '(a b c))))))
  (test-equal #f (and-let* ((even-one (even? 1))) 'body))
  (test-equal #f (and-let* (((even? 1))) 'body))
  (test-equal 'body (and-let* ((even-two (even? 2))) 'body))
  (test-equal '(b c) (and-let* ((b+ (memq 'b '(a b c)))) b+))
  (test-equal '((b c) (c))
    (results (lambda ()
               (and-let* ((abc '(a b c))
                          (b+ (memq 'b abc))
                          (c+ (memq 'c abc))
                          ((eq? (cdr b+) c+)))
                 (values b+ c+)))))
  (test-equal '(1 2) (results (lambda () (and-let* () (values 1 2)))))
  (test-equal #t (and-let* ((a b (values 1 2)))))
  (test-equal #t (and-let* (((values a b) (values 1 2)))))
  (test-equal #t (and-let* ((a b (values 1 2 3)))))
  (test-equal #f (and-let* (((values a b) (values 1 2 3)))))
  (test-equal '(1 2 (3))
    (results (lambda ()
               (and-let* (((values a b . c) (values 1 2 3)))
                 (values a b c)))))
  (test-equal #f (and-let* ((a b (values #f #t)))))
  (test-equal #t (and-let* (((values a b) (values #f #t)))))
  (test-equal #t (and-let* ((`,a b (values #f #t)))))
  (test-equal #t (and-let* (((or a) b (values #f #t)))))
  (test-equal #t (and-let* ((#f b (values #f #t)))))
  (test-equal #f (and-let* (((values a b) (values #f #t)) (a))))
  (test-equal #f (and-let* ((`(,x . ,y) '()))))
  (test-equal #f (and-let* ((`(,x ,y) '(1 2 3)))))
  (test-equal #f (and-let* ((5 (+ 2 2)))))
  (test-equal #f (and-let* ((#t #f #t (values #f #t #f)))))
  (test-equal 2
    (and-let* ((`(,x ,y) '(2 3))
               (x+y (+ x y))
               ((odd? x+y))
               (5 x+y))
      x))
  ;; Not among the examples: a body with definitions.
  (test-equal 6 (and-let* ((x 3)) (define y (* 2 x)) y)))

(test-begin "srfi-202")
(examples)
(let ((failures (test-runner-fail-count (test-runner-current))))
  (test-end "srfi-202")
  (exit (if (zero? failures) 0 1)))
