;;; Tests for SRFI 203.  The picture language's output is an SVG file,
;;; so these tests read the file back.  The painters are the contrib
;;; implementation's test (reference/srfi-203/test-r7rs.scm) and the
;;; SRFI document's example (the SICP helpers, in unit coordinates).
(import (scheme base) (scheme cxr) (scheme file) (scheme read) (scheme write)
        (scheme process-context) (srfi 64) (srfi 203))

(define (make-vect x y . o) (append (list x y) o))
(define (xcor-vect v) (car v))
(define (ycor-vect v) (cadr v))
(define (add-vect v1 v2)
  (make-vect (+ (xcor-vect v1) (xcor-vect v2)) (+ (ycor-vect v1) (ycor-vect v2))))
(define (sub-vect v1 v2)
  (make-vect (- (xcor-vect v1) (xcor-vect v2)) (- (ycor-vect v1) (ycor-vect v2))))
(define (scale-vect s v) (make-vect (* s (xcor-vect v)) (* s (ycor-vect v))))
(define (make-frame origin edge1 edge2) (list origin edge1 edge2))
(define (origin-frame frame) (car frame))
(define (edge1-frame frame) (cadr frame))
(define (edge2-frame frame) (caddr frame))
(define (frame-coord-map frame)
  (lambda (v)
    (add-vect (origin-frame frame)
              (add-vect (scale-vect (xcor-vect v) (edge1-frame frame))
                        (scale-vect (ycor-vect v) (edge2-frame frame))))))
(define (transform-painter painter origin corner1 corner2)
  (lambda (frame)
    (let* ((m (frame-coord-map frame))
           (new-origin (m origin)))
      (painter (make-frame new-origin
                           (sub-vect (m corner1) new-origin)
                           (sub-vect (m corner2) new-origin))))))
(define (flip-vert painter)
  (transform-painter painter (make-vect 0 1) (make-vect 1 1) (make-vect 0 0)))
(define (beside painter1 painter2)
  (let* ((split-point (make-vect 0.5 0))
         (paint-left (transform-painter painter1 (make-vect 0 0) split-point (make-vect 0 1)))
         (paint-right (transform-painter painter2 split-point (make-vect 1 0) (make-vect 0.5 1))))
    (lambda (frame) (paint-left frame) (paint-right frame))))
(define (below painter1 painter2)
  (let* ((split-point (make-vect 0.0 0.5))
         (paint-bottom (transform-painter painter1 split-point (make-vect 1.0 0.5) (make-vect 0.0 1.0)))
         (paint-top (transform-painter painter2 (make-vect 0.0 0.0) (make-vect 1.0 0.0) split-point)))
    (lambda (frame) (paint-bottom frame) (paint-top frame))))
;; a segment painter, SICP 2.2.4
(define (segments->painter segment-list)
  (lambda (frame)
    (for-each (lambda (segment)
                (draw-line ((frame-coord-map frame) (car segment))
                           ((frame-coord-map frame) (cadr segment))))
              segment-list)))

(define (file->string name)
  (call-with-input-file name
    (lambda (in)
      (let loop ((acc '()))
        (let ((c (read-char in)))
          (if (eof-object? c) (list->string (reverse acc)) (loop (cons c acc))))))))
(define (count-occurrences needle hay)
  (let ((n (string-length needle)) (m (string-length hay)))
    (let loop ((i 0) (count 0))
      (cond ((> (+ i n) m) count)
            ((string=? needle (substring hay i (+ i n))) (loop (+ i 1) (+ count 1)))
            (else (loop (+ i 1) count))))))
(define (contains? needle hay) (> (count-occurrences needle hay) 0))

(define path "srfi-203-test.svg")

(test-begin "srfi-203")

(parameterize ((canvas-path path))
  (test-equal "srfi-203-test.svg" (canvas-name))
  ;; drawing works with no set-up
  (canvas-reset)
  (draw-line (make-vect 0 0) (make-vect 1 1))
  (test-equal (string-append "file://" path) (canvas-refresh))
  (test-assert (file-exists? path))
  (let ((svg (file->string path)))
    (test-assert (contains? "<svg" svg))
    (test-assert (contains? "xmlns=\"http://www.w3.org/2000/svg\"" svg))
    (test-equal 1 (count-occurrences "<line" svg))
    ;; unit coordinates, y up: (0,0) is the bottom left corner
    (test-assert (contains? "x1=\"0\" y1=\"256\" x2=\"256\" y2=\"0\"" svg)))

  ;; the SRFI's example: Rogers, a line and an image painter
  (canvas-reset)
  (rogers (make-frame (make-vect 0.5 0.5) (make-vect 0.5 0.0) (make-vect 0.0 0.5)))
  (draw-line (make-vect 0.5 0.5) (make-vect 0 1.0))
  ((jpeg-file->painter "lambda.jpg")
   (make-frame (make-vect 0.5 0.0) (make-vect 0.5 0.1) (make-vect 0.1 0.5)))
  (canvas-refresh)
  (let ((svg (file->string path)))
    (test-equal 2 (count-occurrences "<image" svg))
    (test-assert (contains? "data:image/jpeg;base64," svg))
    (test-assert (contains? "xlink:href=\"lambda.jpg\"" svg))
    (test-assert (contains? "matrix(128.0, 0, 0, 128.0, 128.0, 0)" svg))
    (test-assert (contains? "x1=\"128.0\" y1=\"128.0\" x2=\"0\" y2=\"0\"" svg)))

  ;; the contrib test: rogers4
  (canvas-reset)
  (let* ((rogers2 (beside rogers (flip-vert rogers)))
         (rogers4 (below rogers2 rogers2)))
    (rogers4 (canvas-frame)))
  (canvas-refresh)
  (test-equal 4 (count-occurrences "<image" (file->string path)))

  ;; a segment painter: the frame's outline, scaled to a 100-pixel canvas
  (parameterize ((canvas-width 100) (canvas-height 100))
    (canvas-reset)
    ((segments->painter (list (list (make-vect 0 0) (make-vect 1 0))
                              (list (make-vect 1 0) (make-vect 1 1))
                              (list (make-vect 1 1) (make-vect 0 1))
                              (list (make-vect 0 1) (make-vect 0 0))))
     (make-frame (make-vect 0.25 0.25) (make-vect 0.5 0) (make-vect 0 0.5)))
    (canvas-refresh)
    (let ((svg (file->string path)))
      (test-equal 4 (count-occurrences "<line" svg))
      (test-assert (contains? "height=\"100\"" svg))
      (test-assert (contains? "x1=\"25.0\" y1=\"75.0\" x2=\"75.0\" y2=\"75.0\"" svg))))

  (canvas-cleanup)
  (test-assert (not (file-exists? path))))

(let ((failures (test-runner-fail-count (test-runner-current))))
  (test-end "srfi-203")
  (exit (if (zero? failures) 0 1)))
