;;; Tests for SRFI 208, from its specification.
(import (scheme base) (scheme inexact) (scheme process-context) (srfi 64) (srfi 208))
(test-begin "srfi-208")
(define n1 (make-nan #f #t 42))
(test-assert (nan? n1))
(test-assert (not (nan-negative? n1)))
(test-assert (nan-quiet? n1))
(test-equal 42 (nan-payload n1))
(define n2 (make-nan #t #t 7))
(test-assert (nan-negative? n2))
(test-equal 7 (nan-payload n2))
(define n3 (make-nan #f #f 1))
(test-assert (nan? n3))
(test-assert (not (nan-quiet? n3)))
(test-equal 1 (nan-payload n3))
(test-assert (nan=? n1 (make-nan #f #t 42)))
(test-assert (not (nan=? n1 n2)))
(test-assert (not (nan=? n1 (make-nan #f #t 43))))
(define big (- (expt 2 51) 1))
(test-equal big (nan-payload (make-nan #t #t big)))
(test-error (make-nan #f #t (expt 2 51)))
(test-assert (nan-quiet? (/ 0.0 0.0)))
(let ((failures (test-runner-fail-count (test-runner-current))))
  (test-end "srfi-208")
  (exit (if (zero? failures) 0 1)))
