;;; Tests for SRFI 258, after Wolfgang Corcoran-Mathe's portable test suite.
(import (scheme base) (scheme write) (scheme process-context) (srfi 64) (srfi 258))
(test-begin "srfi-258")
(test-assert (symbol? (string->uninterned-symbol "x")))
(test-assert (symbol? (generate-uninterned-symbol)))
(test-assert (not (eqv? (string->uninterned-symbol "x") (string->uninterned-symbol "x"))))
(test-assert (not (eqv? (generate-uninterned-symbol) (generate-uninterned-symbol))))
(test-assert (not (eq? (string->uninterned-symbol "x") 'x)))
(test-equal "x" (symbol->string (string->uninterned-symbol "x")))
(test-assert (not (symbol-interned? (string->uninterned-symbol "x"))))
(test-assert (not (symbol-interned? (generate-uninterned-symbol))))
(test-assert (not (symbol-interned? (generate-uninterned-symbol "pre"))))
(test-assert (not (symbol-interned? (generate-uninterned-symbol 'pre))))
(test-assert (symbol-interned? 'x))
(test-assert (symbol-interned? (string->symbol "y")))
(test-assert (let ((s (generate-uninterned-symbol "pre")))
               (string=? "pre" (substring (symbol->string s) 0 3))))
(test-assert (let ((s (string->uninterned-symbol "x"))) (eq? s s)))
(test-assert (let ((s (string->uninterned-symbol "x")))
               (not (eq? s (string->symbol (symbol->string s))))))
(let ((failures (test-runner-fail-count (test-runner-current))))
  (test-end "srfi-258")
  (exit (if (zero? failures) 0 1)))
