;;; Tests for SRFI 259, from its specification.
(import (scheme base) (scheme process-context) (srfi 64) (srfi 259))
(test-begin "srfi-259")
(define-procedure-tag make-a a? a-tag)
(define-procedure-tag make-b b? b-tag)
(define (add x y) (+ x y))
(define p (make-a 'one add))
(test-equal 5 (p 2 3))
(test-assert (a? p))
(test-assert (not (b? p)))
(test-assert (not (a? add)))
(test-assert (not (a? 'x)))
(test-assert (procedure? p))
(test-equal 'one (a-tag p))
(test-assert (not (eq? p add)))
(test-assert (not (eqv? (make-a 'one add) (make-a 'one add))))
;; tags in two protocols, and replacing one
(define q (make-b 'two p))
(test-assert (and (a? q) (b? q)))
(test-equal '(one two) (list (a-tag q) (b-tag q)))
(define r (make-a 'three q))
(test-equal '(three two) (list (a-tag r) (b-tag r)))
(test-equal 7 (r 3 4))
(test-error (b-tag p))
;; generative: each evaluation makes a new protocol
(define (make-protocol)
  (define-procedure-tag make-c c? c-tag)
  (list make-c c? c-tag))
(let ((p1 (make-protocol)) (p2 (make-protocol)))
  (test-assert ((cadr p1) ((car p1) 1 add)))
  (test-assert (not ((cadr p2) ((car p1) 1 add)))))
(let ((failures (test-runner-fail-count (test-runner-current))))
  (test-end "srfi-259")
  (exit (if (zero? failures) 0 1)))
