;;; Tests for SRFI 58: its examples, read as SRFI 164 arrays.
(import (scheme base) (scheme read) (scheme process-context) (srfi 64)
        (srfi 58) (srfi 164))
(define (r s) (read (open-input-string s)))
(test-begin "srfi-58")
(define a (r "#2A((0 1 2) (3 5 4))"))
(test-eqv 2 (array-rank a))
(test-eqv 5 (array-ref a 1 1))
(test-eqv 3 (array-end a 1))
(test-eqv 'x (array-ref (r "#0A x")))
(test-eqv -2 (array-ref (r "#1A:fixZ32b(1 -2 3)") 1))
(test-eqv #t (array-ref (r "#1A:bool(#t #f)") 0))
(test-eqv 4 (array-ref #2A((1 2) (3 4)) 1 1))
(let ((failures (test-runner-fail-count (test-runner-current))))
  (test-end "srfi-58")
  (exit (if (zero? failures) 0 1)))
