;;; SRFI 90 tests, after the examples in the SRFI document (the SRFI has
;;; no test suite).
(import (scheme base) (scheme process-context) (scheme char)
        (srfi 64) (srfi 69) (srfi 90))

(test-begin "srfi-90")

(define t1 (make-table))
(define t2 (make-table size: 1000))
(define t3 (make-table hash: string-length))
(define t4 (make-table test: eq? weak-keys: #t))

(test-assert (hash-table? t1))
(test-assert (hash-table? t2))
(test-assert (hash-table? t3))
(test-assert (hash-table? t4))
(test-eq equal? (hash-table-equivalence-function t1))
(test-eq eq? (hash-table-equivalence-function t4))

(hash-table-set! t1 (list 1 2) 'a)
(test-equal 'a (hash-table-ref/default t1 (list 1 2) #f))
(hash-table-set! t3 "abc" 1)
(hash-table-set! t3 "xyz" 2)
(test-equal 1 (hash-table-ref/default t3 (string #\a #\b #\c) #f))
(test-equal 2 (hash-table-ref/default t3 "xyz" #f))
(test-equal 2 (hash-table-size t3))
(hash-table-set! t4 (list 1) 'x)
(test-equal #f (hash-table-ref/default t4 (list 1) #f))

(define obj2sn (make-table test: eq? weak-keys: #t))
(define sn2obj (make-table test: equal? weak-values: #t))
(define last-sn 0)
(define (object->serial-number obj)
  (or (hash-table-ref/default obj2sn obj #f)
      (let ((sn (+ last-sn 1)))
        (set! last-sn sn)
        (hash-table-set! obj2sn obj sn)
        (hash-table-set! sn2obj sn obj)
        sn)))
(define (serial-number->object sn)
  (hash-table-ref/default sn2obj sn #f))
(define obj1 (list 1 11))
(define obj2 (list 2 22))
(define obj3 (list 3 33))
(test-equal 1 (object->serial-number obj1))
(test-equal 2 (object->serial-number obj2))
(test-equal 1 (object->serial-number obj1))
(set! obj2 'void)
(test-equal 3 (object->serial-number obj3))
(test-equal '(1 11) (serial-number->object 1))
(test-assert (member (serial-number->object 2) '((2 22) #f)))

;; Other spellings of the parameter names, and both test and hash.
(let ((t (make-table #:test string-ci=? #:hash (lambda (s) 0))))
  (hash-table-set! t "Key" 1)
  (test-equal 1 (hash-table-ref/default t "KEY" #f)))
(let ((t (make-table 'test: eqv? 'min-load: 0.25 'max-load: 0.75)))
  (test-eq eqv? (hash-table-equivalence-function t)))

(test-error (make-table size: -1))
(test-error (make-table min-load: 0.9 max-load: 0.5))
(test-error (make-table 'frobnicate: 3))
(test-error (make-table test:))

(let ((failures (test-runner-fail-count (test-runner-current))))
  (test-end "srfi-90")
  (exit (if (zero? failures) 0 1)))
