;;; Tests for SRFI 96, from the SRFI document's specification and
;;; examples.
(import (scheme base) (scheme char) (except (scheme file) delete-file) (scheme read)
        (scheme write) (scheme process-context) (srfi 64) (srfi 96))

(test-begin "srfi-96")

;; Configuration
(test-equal 'unix (software-type))
(test-equal 'pseudoscheme (scheme-implementation-type))
(test-equal "3.0" (scheme-implementation-version))
(test-assert (let ((h (scheme-implementation-home-page))) (or (not h) (string? h))))
(test-equal ".scm" (scheme-file-suffix))
(test-assert (memq 'vicinity slib:features))
(test-assert (exact-integer? most-positive-fixnum))
(test-assert (> most-positive-fixnum 1000000))
(test-assert (> char-code-limit (char->integer #\λ)))

;; File system
(define tmp (tmpnam))
(test-assert (string? tmp))
(test-assert (not (equal? tmp (tmpnam))))
(test-assert (not (file-exists? tmp)))
(test-equal #f (delete-file tmp))
(call-with-output-file tmp (lambda (out) (write '(define slib-test-value 42) out)))
(test-assert (file-exists? tmp))
(test-equal "here/" (with-load-pathname "here/x.scm" program-vicinity))
(test-equal 17 (with-load-pathname "x.scm" (lambda () 17)))

;; Input/output
(test-equal '(define slib-test-value 42)
  (call-with-open-ports (open-file tmp 'r) read))
(test-equal '(define slib-test-value 42)
  (call-with-open-ports read (open-file tmp 'r)))
(test-equal 40
  (let ((p (open-file tmp 'rb)))
    (call-with-open-ports p (lambda (p) (read-u8 p)))))
(let ((p (open-file tmp 'r)))
  (test-equal 0 (file-position p))
  (read-char p)
  (test-equal 1 (file-position p))
  (test-assert (file-position p 0))
  (test-equal #\( (read-char p))
  (close-port p))
(test-assert (port? (current-error-port)))
(force-output)
(force-output (current-output-port))
(test-equal 79 (output-port-width))
(test-equal 24 (output-port-height (current-output-port)))

;; System: evaluating and loading at the REPL's top level
(test-equal 3 (slib:eval '(+ 1 2)))
(slib:eval '(define slib-test-x 10))
(test-equal 10 (slib:eval 'slib-test-x))
(slib:load-source tmp)
(test-equal 42 (slib:eval 'slib-test-value))
(test-assert (delete-file tmp))
(define base (string-append (tmpnam) "-src"))
(call-with-output-file (string-append base ".scm")
  (lambda (out)
    (write '(define slib-loaded-from (program-vicinity)) out)
    (write '(defmacro slib-twice (x) (list 'list x x)) out)))
(slib:load base)
(test-equal (pathname->vicinity base) (slib:eval 'slib-loaded-from))
(test-equal '(5 5) (slib:eval '(slib-twice 5)))
(test-equal 9 (macro:eval '(let-syntax ((m (syntax-rules () ((_ a) (* a a))))) (m 3))))
(test-equal #f (macro:expand '(foo)))
(delete-file (string-append base ".scm"))
(test-error (slib:error "oops" 1 2))
(test-error (slib:load-compiled "nothing"))
(test-equal 0 (system "true"))
(test-assert (not (zero? (system "false"))))
(test-assert (list? (program-arguments)))
(test-equal (get-environment-variable "HOME") (getenv "HOME"))
(test-equal #f (getenv "SRFI_96_SURELY_UNSET"))

;; Defmacro
(defmacro my-unless (test . body) `(if ,test #f (begin ,@body)))
(test-equal 'yes (my-unless #f 'yes))
(test-equal #f (my-unless #t 'yes))
(test-equal '(if c #f (begin x y)) (macroexpand '(my-unless c x y)))
(test-equal '(f (if c #f (begin x)) '(my-unless a b))
  (defmacro:expand* '(f (my-unless c x) '(my-unless a b))))
(test-equal 'ok (defmacro:eval '(my-unless #f 'ok)))
(test-equal '(a b) (macroexpand '(a b)))
(test-assert (symbol? (gentemp)))
(test-assert (not (eq? (gentemp) (gentemp))))

;; Miscellany
(test-equal 3 (identity 3))
(test-equal '(foo bar) (identity '(foo bar)))
(test-equal #\tab slib:tab)
(test-equal 12 (char->integer slib:form-feed))
(test-equal #t t)
(test-equal #f nil)
(test-equal '(1 . 2) (last-pair (cons 1 2)))
(test-equal '(2) (last-pair '(1 2)))

;; make-exchanger, and the SRFI's semaphores on it
(define (make-semaphore v) (make-exchanger v))
(define (run-other-process) #f)
(define (P! s)
  (let loop ()
    (define val (s #f))
    (cond ((and val (positive? val))
           (s (- val 1)))
          (else
           (and val (s val))
           (run-other-process)
           (loop)))))
(define (V! s)
  (let loop ()
    (define val (s #f))
    (cond (val
           (s (+ val 1)))
          (else
           (run-other-process)
           (loop)))))
(define sem (make-semaphore 2))
(P! sem)
(P! sem)
(V! sem)
(test-equal 1 (sem 99))
(test-equal 99 (sem 0))

(let ((failures (test-runner-fail-count (test-runner-current))))
  (test-end "srfi-96")
  (exit (if (zero? failures) 0 1)))
