;;; Tests for SRFI 99, from the examples in the SRFI document and its
;;; specification of define-record-type.
(import (except (scheme base) define-record-type) (scheme process-context)
        (srfi 64) (srfi 99)
        (prefix (srfi 99 records inspection) i:)
        (prefix (srfi 99 records procedural) p:)
        (prefix (srfi 99 records syntactic) s:))

;; Syntactic layer.  The tests' other definitions are internal ones,
;; because Pseudoscheme compiles many top-level calls slowly (see
;; ../57.sld).
(define-record-type point #t #t (x) (y))

(define (example-1)
  (let* ((rtd1 (make-rtd 'rtd1 '#((immutable x1) (immutable x2))))
         (rtd2 (make-rtd 'rtd2 '#((immutable x3) (immutable x4)) rtd1))
         (rtd3 (make-rtd 'rtd3 '#((immutable x5) (immutable x6)) rtd2))
         (protocol1 (lambda (p) (lambda (a b c) (p (+ a b) (+ b c)))))
         (protocol2 (lambda (n)
                      (lambda (a b c d e f)
                        (let ((p (n a b c))) (p (+ d e) (+ e f))))))
         (protocol3 (lambda (n)
                      (lambda (a b c d e f g h i)
                        (let ((p (n a b c d e f))) (p (+ g h) (+ h i))))))
         (make-rtd3
          (let ((maker3 (rtd-constructor rtd3)))
            (protocol3
             (protocol2
              (protocol1
               (lambda (x1 x2)
                 (lambda (x3 x4)
                   (lambda (x5 x6)
                     (maker3 x1 x2 x3 x4 x5 x6)))))))))
         (r (make-rtd3 1 2 3 4 5 6 7 8 9)))
    (test-equal "example 1" '(3 5 9 11 15 17)
      (map (lambda (rtd f) ((rtd-accessor rtd f) r))
           (list rtd1 rtd1 rtd2 rtd2 rtd3 rtd3)
           '(x1 x2 x3 x4 x5 x6)))
    (test-assert "rtd?" (rtd? rtd3))
    (test-assert "rtd? of a non-rtd" (not (rtd? 'rtd3)))
    (test-eq "rtd-parent" rtd2 (rtd-parent rtd3))
    (test-equal "rtd-parent of a base type" #f (rtd-parent rtd1))
    (test-eq "rtd-name" 'rtd3 (rtd-name rtd3))
    (test-equal "rtd-field-names" '#(x5 x6) (rtd-field-names rtd3))
    (test-equal "rtd-all-field-names" '#(x1 x2 x3 x4 x5 x6)
      (rtd-all-field-names rtd3))
    (test-assert "rtd-field-mutable? immutable" (not (rtd-field-mutable? rtd3 'x1)))
    (test-assert "record?" (record? r))
    (test-eq "record-rtd" rtd3 (record-rtd r))))

(define (example-2)
  (let* ((:point (make-rtd 'point '#((mutable x) (mutable y))))
         (make-point (rtd-constructor :point))
         (point? (rtd-predicate :point))
         (point-x (rtd-accessor :point 'x))
         (point-y (rtd-accessor :point 'y))
         (point-x-set! (rtd-mutator :point 'x))
         (p1 (make-point 1 2)))
    (test-assert (point? p1))
    (test-equal 1 (point-x p1))
    (test-equal 2 (point-y p1))
    (point-x-set! p1 5)
    (test-equal 5 (point-x p1))
    (test-assert "rtd-field-mutable? mutable" (rtd-field-mutable? :point 'x))
    (let* ((:point2 (make-rtd 'point2 '#((mutable x) (mutable y)) :point))
           (make-point2 (rtd-constructor :point2))
           (point2? (rtd-predicate :point2))
           (point2-xx (rtd-accessor :point2 'x))
           (point2-yy (rtd-accessor :point2 'y))
           (p2 (make-point2 1 2 3 4)))
      (test-assert (point? p2))
      (test-assert (point2? p2))
      (test-assert (not (point2? p1)))
      (test-equal 1 (point-x p2))
      (test-equal 2 (point-y p2))
      (test-equal 3 (point2-xx p2))
      (test-equal 4 (point2-yy p2)))
    (let ((make-point/abs
           (let ((maker (rtd-constructor :point)))
             (lambda (x y) (maker (abs x) (abs y))))))
      (test-equal 1 (point-x (make-point/abs -1 -2)))
      (test-equal 2 (point-y (make-point/abs -1 -2))))
    ;; A constructor taking some fields by name, and symbols as field specs.
    (let* ((:q (make-rtd 'q '#(a b c)))
           (make-q (rtd-constructor :q '#(c a)))
           (q (make-q 3 1)))
      (test-equal "rtd-constructor with field names" '(1 3)
        (list ((rtd-accessor :q 'a) q) ((rtd-accessor :q 'c) q)))
      (test-assert "symbol field specs are mutable" (rtd-field-mutable? :q 'b)))))

(define (syntactic-tests)
  (define-record-type (point3 point) make-point3 point3? (z point3-z))
  (define-record-type node (make-node val next) node?
    (val node-val)
    (next node-next set-node-next!))
  (define-record-type thing #f thing? name)
  (define-record-type (cpoint point) (make-cpoint x y rgb) cpoint?
    (rgb cpoint-rgb))
  (s:define-record-type pare (kons x y) pare? (x kar) (y kdr set-kdr!))
  (let ((p (make-point 1 2)))
    (test-assert "implicit predicate" (point? p))
    (test-equal "implicit accessors" '(1 2) (list (point-x p) (point-y p)))
    (point-x-set! p 10)
    (test-equal "implicit mutator" 10 (point-x p)))
  (let ((p (make-point3 1 2 3)))
    (test-assert "subtype instance of parent" (point? p))
    (test-assert "subtype predicate" (point3? p))
    (test-assert "parent instance not of subtype" (not (point3? (make-point 1 2))))
    (test-equal "inherited and own fields" '(1 2 3)
      (list (point-x p) (point-y p) (point3-z p)))
    (test-eq "type name bound to the rtd" point (rtd-parent point3)))
  (let ((n (make-node 1 '())))
    (set-node-next! n 'end)
    (test-equal "explicit accessors and mutators" '(1 end)
      (list (node-val n) (node-next n))))
  (test-assert "no constructor, predicate" (not (thing? 3)))
  (test-equal "field spec as a bare symbol" '#(name) (rtd-field-names thing))
  (let ((c (make-cpoint 1 2 'red)))
    (test-equal "constructor with all fields" '(1 2 red)
      (list (point-x c) (point-y c) (cpoint-rgb c))))
  (let ((k (kons 1 2)))
    (set-kdr! k 3)
    (test-equal "sublibraries" '(1 3) (list (kar k) (kdr k)))
    (test-assert "inspection sublibrary" (i:record? k))
    (test-assert "procedural sublibrary" (p:rtd? (i:record-rtd k)))))

(test-begin "srfi-99")
(example-1)
(example-2)
(syntactic-tests)
(let ((failures (test-runner-fail-count (test-runner-current))))
  (test-end "srfi-99")
  (exit (if (zero? failures) 0 1)))
