; -*- Mode: Lisp; Syntax: Common-Lisp; Package: CL-USER; -*-

;;;; Regenerating the translator's bootstrap .pso files.
;;;
;;; The translator itself (p-record.scm, alpha.scm, derive.scm, etc.,
;;; listed in translator.files) is written in Scheme and is normally
;;; loaded pre-translated, as the corresponding .pso files -- that's
;;; what lets :pseudoscheme/translator load without already having a
;;; working Pseudoscheme.
;;;
;;; Whenever one of those .scm files changes, its .pso file is stale
;;; and must be regenerated by asking the (already-loaded, working)
;;; translator to translate itself again. Load this file after loading
;;; :pseudoscheme, then call (PSEUDOSCHEME-BOOTSTRAP:REGENERATE-PSO-FILES).
;;;
;;; After regenerating, always reload :pseudoscheme from a fresh Lisp
;;; image and re-run the test suite (tests/run-r5rs-tests.lisp) before
;;; trusting the new .pso files.

(defpackage :pseudoscheme-bootstrap
  (:use :common-lisp)
  (:export #:regenerate-pso-files #:regenerate-closed-pso))

(in-package :pseudoscheme-bootstrap)

(defun translator-files ()
  (with-open-file (s (asdf:system-relative-pathname :pseudoscheme "translator.files"))
    (read s)))

(defun translator-env ()
  (symbol-value (intern "SCHEME-TRANSLATOR-ENV" "SCHEME-TRANSLATOR")))

(defun regenerate-pso-files (&optional (files (translator-files)))
  "Retranslate each named .scm file (default: all of translator.files)
to its .pso file, using the currently-loaded translator. Returns the
list of files regenerated."
  (let ((env (translator-env)))
    (dolist (file files)
      (format t "~&Regenerating ~A.pso from ~A.scm~%" file file)
      (ps:translate-file file env)))
  files)

(defun regenerate-closed-pso ()
  "CLOSED.PSO isn't translated from a .scm source -- it's synthesized
by WRITE-CLOSED-DEFINITIONS from the *current* builtin integrations
table (see builtin.scm), as real top-level function definitions for
every procedure in REVISED^4-SCHEME-INTERFACE. So it goes stale
whenever builtin.scm's integration table changes (e.g. which CL
function backs a given Scheme procedure, or how its result is
coerced to a Scheme boolean), even though no line of CLOSED.PSO
itself changed. Call this after such a change, then always do a full
REGENERATE-PSO-FILES + fresh-image reload + test run before trusting
the result, same as for the other bootstrap files."
  (funcall (intern "WRITE-CLOSED-DEFINITIONS" "SCHEME-TRANSLATOR")
	   (symbol-value (intern "REVISED^4-SCHEME-STRUCTURE" "SCHEME-TRANSLATOR"))
	   (asdf:system-relative-pathname :pseudoscheme "closed.pso")))
