; -*- Mode: Lisp; Syntax: Common-Lisp; Package: CL-USER; -*-

;;;; Regenerating the translator's bootstrap .pso files.
;;;
;;; The translator itself (p-record.scm, alpha.scm, derive.scm, etc.,
;;; listed in translator.files) is written in Scheme and is normally
;;; loaded pre-translated, as the corresponding .pso files -- that's
;;; what lets :pseudoscheme/translator load without already having a
;;; working Pseudoscheme.
;;;
;;; Whenever one of those .scm files changes, its .pso file is stale
;;; and must be regenerated by asking the (already-loaded, working)
;;; translator to translate itself again. Load this file after loading
;;; :pseudoscheme, then call (PSEUDOSCHEME-BOOTSTRAP:REGENERATE-PSO-FILES).
;;;
;;; After regenerating, always reload :pseudoscheme from a fresh Lisp
;;; image and re-run the test suite (tests/run-r5rs-tests.lisp) before
;;; trusting the new .pso files.

(defpackage :pseudoscheme-bootstrap
  (:use :common-lisp)
  (:export #:regenerate-pso-files #:regenerate-closed-pso
	   #:regenerate-reader-writer))

(in-package :pseudoscheme-bootstrap)

(defun src-directory ()
  ;; NB: not ASDF:SYSTEM-RELATIVE-PATHNAME / ASDF:SYSTEM-SOURCE-DIRECTORY
  ;; -- those give the directory of the .asd file itself (the repo
  ;; root), not a system's :PATHNAME. The .scm/.pso files live under
  ;; src/, where :pseudoscheme's components actually are.
  (asdf:component-pathname (asdf:find-system :pseudoscheme)))

(defun translator-files ()
  (with-open-file (s (merge-pathnames "translator.files" (src-directory)))
    (read s)))

(defun translator-env ()
  (symbol-value (intern "SCHEME-TRANSLATOR-ENV" "SCHEME-TRANSLATOR")))

(defmacro with-bootstrap-reader (&body body)
  ;; Bootstrap regeneration must always use the CL-reader bridge
  ;; (ps:scheme-read-using-commonlisp-reader), regardless of what
  ;; ps:*scheme-read* currently is -- if :pseudoscheme/reader has also
  ;; been loaded in this image (e.g. for R5RS work), the dedicated
  ;; Scheme48-derived reader it installs can't resolve the CL
  ;; package-qualified symbols (PS-LISP:SETF and friends) the
  ;; translator's own sources rely on. See README.md.
  ;;
  ;; Also binds *DEFAULT-PATHNAME-DEFAULTS* to src/ (where the .scm/.pso
  ;; files actually live, since pseudoscheme.asd itself is at the repo
  ;; root) -- PS:TRANSLATE-FILE resolves bare filenames like "ssig"
  ;; against *DEFAULT-PATHNAME-DEFAULTS*, not against the .asd.
  `(let ((ps:*scheme-read* #'ps:scheme-read-using-commonlisp-reader)
	 (*default-pathname-defaults* (src-directory)))
     ,@body))

(defun regenerate-pso-files (&optional (files (translator-files)))
  "Retranslate each named .scm file (default: all of translator.files)
to its .pso file, using the currently-loaded translator. Returns the
list of files regenerated."
  (with-bootstrap-reader
    (let ((env (translator-env)))
      (dolist (file files)
	(format t "~&Regenerating ~A.pso from ~A.scm~%" file file)
	(ps:translate-file file env))))
  files)

(defun regenerate-closed-pso ()
  "CLOSED.PSO isn't translated from a .scm source -- it's synthesized
by WRITE-CLOSED-DEFINITIONS from the *current* builtin integrations
table (see builtin.scm), as real top-level function definitions for
every procedure in REVISED^4-SCHEME-INTERFACE. So it goes stale
whenever builtin.scm's integration table changes (e.g. which CL
function backs a given Scheme procedure, or how its result is
coerced to a Scheme boolean), even though no line of CLOSED.PSO
itself changed. Call this after such a change, then always do a full
REGENERATE-PSO-FILES + fresh-image reload + test run before trusting
the result, same as for the other bootstrap files."
  (with-bootstrap-reader
    (funcall (intern "WRITE-CLOSED-DEFINITIONS" "SCHEME-TRANSLATOR")
	     (symbol-value (intern "REVISED^4-SCHEME-STRUCTURE" "SCHEME-TRANSLATOR"))
	     (merge-pathnames "closed.pso" (src-directory)))))

(defun regenerate-reader-writer ()
  "Retranslate read.scm/write.scm (the dedicated Scheme48-derived
reader/writer, :pseudoscheme/reader) using the translator, same as
REGENERATE-PSO-FILES does for the translator's own sources. These
target REVISED^4-SCHEME-ENV, not SCHEME-TRANSLATOR-ENV, since they're
ordinary runtime code, not part of the translator itself."
  (with-bootstrap-reader
    (let ((env (symbol-value (intern "REVISED^4-SCHEME-ENV" "SCHEME-TRANSLATOR"))))
      (dolist (file '("read" "write"))
	(format t "~&Regenerating ~A.pso from ~A.scm~%" file file)
	(ps:translate-file file env))))
  '("read" "write"))
